const dns = require("node:dns");
dns.setServers(["8.8.8.8", "8.8.4.4"]);

import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";

const manrope = Manrope({
  subsets: ["latin"],
});
export const metadata = {
  title: "Ashik Hireloop for Job Seekers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="dark"
      lang="en"
      className={`${manrope.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <Navbar />
        <main>
          {children}
          <ToastContainer
            position="top-right"
            autoClose={3000}
            theme="dark"
            newestOnTop />
        </main>
        <Footer />
      </body>
    </html>
  );
}
